spring:
  security:
    oauth2:
      authorizationserver:
        client:
          crm-client:
            require-authorization-consent: true
            registration:
              client-id: crm
              client-secret: "{bcrypt}$2a$10$HcfomKj/YG5eZ2fE9XEtUutsw7aFy.rtGNpW9Rj5AM00s49F3tC7i"
              authorization-grant-types: client_credentials, authorization_code, refresh_token
              redirect-uris: http://127.0.0.1:8082/login/oauth2/code/spring
              scopes: user.read,user.write,openid
              client-authentication-methods: client_secret_basic
